.\"
.\"Copyright (c) 2019 Joseph Fierro <joseph.fierro@runbox.com>
.\"
.\"Permission to use, copy, modify, and distribute this software for any
.\"purpose with or without fee is hereby granted, provided that the above
.\"copyright notice and this permission notice appear in all copies.
.\"
.\"THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\"WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\"MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\"ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\"WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\"ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\"OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: March 2 2019 $
.Dt STANDOFF 1
.Os
.Sh NAME
.Nm standoff
.Nd Easy automated remote configuration tool
.Sh SYNOPSIS
.Nm standoff.pl
.Fl f Ar payload_file
.Sh DESCRIPTION
The
.Nm
tool performs automated remote configuration of servers via SSH.
It takes a payload file as its argument, containing a section for
.Bl -tag -width Dsssigfile
.It Fl f Ar payload_file
The payload file. This is a text file in INI format.
.El
.Pp
