.\"
.\"Copyright (c) 2020 Joseph Fierro <joseph.fierro@runbox.com>
.\"
.\"Permission to use, copy, modify, and distribute this software for any
.\"purpose with or without fee is hereby granted, provided that the above
.\"copyright notice and this permission notice appear in all copies.
.\"
.\"THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\"WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\"MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\"ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\"WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\"ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\"OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd $Mdocdate: April 18 2020 $
.Dt STANDOFF 1
.Os
.Sh NAME
.Nm standoff
.Nd Easy automated remote configuration tool
.Sh SYNOPSIS
.Nm standoff.pl
.Op Fl p
.Fl f Ar payload_file
.Op Fl f Ar payload_file2
.Sh DESCRIPTION
The
.Nm
tool performs automated remote configuration of servers via SSH.
The following options determine behavior: 
.Bl -tag -width Dsssigfile
.It Fl f Ar payload_file
The payload file. This is a text file in INI format (see examples below for format).
Multiple payload files may be
given by specifying the -f option again. 
.It Fl p
Run
.Nm
in "pull mode".
.Nm
will connect to the target in the [Target] section, download the files listed in the 
[Files] section of the payload file,
and then execute all commands in the [Commands] section locally.
.El
.Sh EXAMPLES
.Pp
An example of a simple, valid payload file is as follows:
.Dl [Target]
.Dl target=172.16.1.1
.Dl ssh_key=/path/to/ssh/key

.Dl [Files]
.Dl file=httpd.conf

.Dl [Commands]
.Dl command=doas cp httpd.conf /etc
.Dl command=doas rcctl reload httpd
.Pp
To run this payload, execute the following:
.Dl $ standoff -f payload_file 
.Pp
This will first connect to the target, 172.16.1.1, using the SSH key found at /path/to/ssh_key.
It will upload the file "httpd.conf" to the remote user's home directory, then execute the commands
in order. Files are always uploaded before commands are run.
.Pp
If either the [Commands] or [Files] sections is not present,
.Nm
will simply ignore that section. Likewise, the ssh_key parameter in the [Target] section is
optional. 
.Nm
will attempt to connect via passphrase-based authentication if it is not supplied.
.Sh AUTHOR
Joseph Fierro <joseph.fierro@runbox.com>
